### ISSUE TITLE
Errors when running v0.0.2

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-sync-sia#14]
issue while running v.0.0.2:

```
2017/11/21 12:24:53 DEBUG net.harawata.appdirs.AppDirsFactory - os.name windows 10 is resolved to Windows
2017/11/21 12:24:54 INFO  io.goobox.sync.sia.Config - Loading config file C:\Users\meije\AppData\Local\Goobox\goobox.properties
2017/11/21 12:24:54 WARN  io.goobox.sync.sia.Config - Invalid data pieces null, use 1 instead
2017/11/21 12:24:54 WARN  io.goobox.sync.sia.Config - Invalid parity pieces null, use 12 instead
2017/11/21 12:24:54 INFO  io.goobox.sync.sia.App - Checking if local Goobox sync folder exists: C:\Users\meije\Goobox
2017/11/21 12:24:54 DEBUG net.harawata.appdirs.AppDirsFactory - os.name windows 10 is resolved to Windows
2017/11/21 12:24:54 INFO  io.goobox.sync.sia.App - Checking if Goobox data folder exists: C:\Users\meije\AppData\Local\Goobox
2017/11/21 12:24:54 DEBUG net.harawata.appdirs.AppDirsFactory - os.name windows 10 is resolved to Windows
2017/11/21 12:24:54 INFO  io.goobox.sync.sia.App - Unlocking a wallet
2017/11/21 12:24:55 INFO  io.goobox.sync.sia.App - Address of the wallet is 3212dbb3a86a7f8777eeb4c671f00c0ca6716baa71f4b3cf22d7e9a03613822149d19549e8a7
2017/11/21 12:24:55 INFO  io.goobox.sync.sia.CheckConsensusTask - Checking siad is synchronized
2017/11/21 12:24:55 INFO  io.goobox.sync.sia.CheckContractsTask - Checking contracts
Exception in thread "Thread-0" com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 2361393152 at line 1 column 8701 path $.contracts[2].size
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:227)
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:217)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
        at com.google.gson.Gson.fromJson(Gson.java:887)
        at com.google.gson.Gson.fromJson(Gson.java:852)
        at com.google.gson.Gson.fromJson(Gson.java:801)
        at io.goobox.sync.sia.client.JSON.deserialize(JSON.java:103)
        at io.goobox.sync.sia.client.ApiClient.deserialize(ApiClient.java:859)
        at io.goobox.sync.sia.client.ApiClient.handleResponse(ApiClient.java:1062)
        at io.goobox.sync.sia.client.ApiClient.execute(ApiClient.java:989)
        at io.goobox.sync.sia.client.api.RenterApi.renterContractsGetWithHttpInfo(RenterApi.java:142)
        at io.goobox.sync.sia.client.api.RenterApi.renterContractsGet(RenterApi.java:129)
        at io.goobox.sync.sia.CheckContractsTask.run(CheckContractsTask.java:52)
        at io.goobox.sync.storj.TaskExecutor.run(TaskExecutor.java:34)
Caused by: java.lang.NumberFormatException: Expected an int but was 2361393152 at line 1 column 8701 path $.contracts[2].size
        at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1172)
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:225)
        ... 19 more
Press any key to continue . . .
```

when listing the database content:

```
2017/11/21 12:26:40 DEBUG net.harawata.appdirs.AppDirsFactory - os.name windows 10 is resolved to Windows
Press any key to continue . . .
```

OS: windows 10, 64bit

**Comment by MeijeSibbel** [comment]
First line in the database, `sync.sia.db`:

```
H:2,blockSize:1000,created:15fde5481e3,format:1,fletcher:b809a24a
```

After that the next two lines show `Null` in Notepad++

**Comment by MeijeSibbel** [comment]
![sia_screenshot](https://user-images.githubusercontent.com/11735738/33070433-47ec3ecc-ceb8-11e7-8773-a6d7fe05da02.png)
