### ISSUE TITLE
v0.0.8 crashes on windows

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-sync-sia#19]
```
2017/12/09 13:29:54 INFO  io.goobox.sync.sia.SiaDaemon - Downloading consensus database... (8227 MB)
2017/12/09 13:29:59 INFO  io.goobox.sync.sia.SiaDaemon - Downloading consensus database... (8245 MB)
2017/12/09 13:30:04 INFO  io.goobox.sync.sia.SiaDaemon - Downloading consensus database... (8265 MB)
2017/12/09 13:30:09 INFO  io.goobox.sync.sia.SiaDaemon - Downloading consensus database... (8293 MB)
2017/12/09 13:30:14 INFO  io.goobox.sync.sia.App - Waiting SIA daemon starts
```2017/12/09 14:18:00 INFO  io.goobox.sync.sia.SiaDaemon - Starting SIA daemon
2017/12/09 14:18:00 DEBUG io.goobox.sync.sia.SiaDaemon - Execute: C:\Users\meije\Downloads\goobox-sync-sia-0.0.8-win64\goobox-sync-sia-0.0.8-win64\Sia\siad.exe --api-addr=127.0.0.1:9980 --host-addr=:9982 --rpc-addr=:9981 --sia-directory=C:\Users\meije\AppData\Local\Goobox\sia --modules=cghrtw
2017/12/09 14:18:00 DEBUG io.goobox.sync.sia.SiaDaemon - Loading...
2017/12/09 14:18:00 DEBUG io.goobox.sync.sia.SiaDaemon - (0/6) Loading siad...
2017/12/09 14:18:00 DEBUG io.goobox.sync.sia.SiaDaemon - (1/6) Loading gateway...
2017/12/09 14:18:00 DEBUG io.goobox.sync.sia.SiaDaemon - (2/6) Loading consensus...
2017/12/09 14:18:00 DEBUG io.goobox.sync.sia.SiaDaemon - (3/6) Loading transaction pool...
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
        at com.google.gson.Gson.fromJson(Gson.java:887)
        at com.google.gson.Gson.fromJson(Gson.java:852)
        at com.google.gson.Gson.fromJson(Gson.java:801)
        at com.google.gson.Gson.fromJson(Gson.java:773)
        at io.goobox.sync.sia.APIUtils.getErrorMessage(APIUtils.java:37)
        at io.goobox.sync.sia.App.init(App.java:238)
        at io.goobox.sync.sia.App.main(App.java:161)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $
at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
... 7 more
2017/12/09 14:26:57 DEBUG io.goobox.sync.sia.SiaDaemon - (4/6) Loading wallet...
2017/12/09 14:26:57 DEBUG io.goobox.sync.sia.SiaDaemon - (5/6) Loading host...
2017/12/09 14:59:40 DEBUG io.goobox.sync.sia.SiaDaemon - goroutine 261 [running]:
2017/12/09 14:59:40 DEBUG io.goobox.sync.sia.SiaDaemon - runtime/debug.Stack(0x44439e, 0x0, 0xc042409a78)
2017/12/09 14:59:40 DEBUG io.goobox.sync.sia.SiaDaemon - /usr/local/go/src/runtime/debug/stack.go:24 +0x80
2017/12/09 14:59:40 DEBUG io.goobox.sync.sia.SiaDaemon - runtime/debug.PrintStack()
2017/12/09 14:59:40 DEBUG io.goobox.sync.sia.SiaDaemon - /usr/local/go/src/runtime/debug/stack.go:16 +0x29
2017/12/09 14:59:40 DEBUG io.goobox.sync.sia.SiaDaemon - github.com/NebulousLabs/Sia/build.Severe(0xc042409bf0, 0x2, 0x2)
2017/12/09 14:59:40 DEBUG io.goobox.sync.sia.SiaDaemon - /home/luke/go/src/github.com/NebulousLabs/Sia/build/critical.go:32 +0x99
2017/12/09 14:59:40 DEBUG io.goobox.sync.sia.SiaDaemon - github.com/NebulousLabs/Sia/persist.(*Logger).Severe(0xc05b2592e0, 0xc042409bf0, 0x2, 0x2)
2017/12/09 14:59:40 DEBUG io.goobox.sync.sia.SiaDaemon - /home/luke/go/src/github.com/NebulousLabs/Sia/persist/log.go:71 +0xe7
2017/12/09 14:59:40 DEBUG io.goobox.sync.sia.SiaDaemon - github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).syncResources(0xc08683b628)
2017/12/09 14:59:40 DEBUG io.goobox.sync.sia.SiaDaemon - /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:110 +0x6b0
2017/12/09 14:59:40 DEBUG io.goobox.sync.sia.SiaDaemon - github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).commit(0xc08683b628)
2017/12/09 14:59:40 DEBUG io.goobox.sync.sia.SiaDaemon - /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:147 +0x47
2017/12/09 14:59:40 DEBUG io.goobox.sync.sia.SiaDaemon - github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).threadedSyncLoop(0xc08683b628, 0xc08e12ff20, 0xc08e12ff80)
2017/12/09 14:59:40 DEBUG io.goobox.sync.sia.SiaDaemon - /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:276 +0x149
2017/12/09 14:59:40 DEBUG io.goobox.sync.sia.SiaDaemon - created by github.com/NebulousLabs/Sia/modules/host/contractmanager.(*writeAheadLog).spawnSyncLoop
2017/12/09 14:59:40 DEBUG io.goobox.sync.sia.SiaDaemon - /home/luke/go/src/github.com/NebulousLabs/Sia/modules/host/contractmanager/writeaheadlogsync.go:223 +0x103
2017/12/09 14:59:40 DEBUG io.goobox.sync.sia.SiaDaemon - Severe error: ERROR: could not rename temporary write-ahead-log in contract manager: rename C:\Users\meije\AppData\Local\Goobox\sia\host\contractmanager\contractmanager.wal_temp C:\Users\meije\AppData\Local\Goobox\sia\host\contractmanager\contractmanager.wal: Access is denied.
2017/12/09 17:05:47 DEBUG io.goobox.sync.sia.SiaDaemon - Closing host...
2017/12/09 17:05:56 DEBUG io.goobox.sync.sia.SiaDaemon - Closing wallet...
2017/12/09 17:05:56 DEBUG io.goobox.sync.sia.SiaDaemon - Closing transaction pool...
2017/12/09 17:05:56 DEBUG io.goobox.sync.sia.SiaDaemon - Closing consensus...
2017/12/09 17:05:56 DEBUG io.goobox.sync.sia.SiaDaemon - Closing gateway...
2017/12/09 17:06:15 DEBUG io.goobox.sync.sia.SiaDaemon - invalid argument
C:\Users\meije\Downloads\goobox-sync-sia-0.0.8-win64\goobox-sync-sia-0.0.8-win64\bin>
```

- After this it just closes the batch file.
- windows 10 home, 64 bit, Version    10.0.16299 Build 16299

**Comment by jkawamoto** [comment]
https://github.com/NebulousLabs/Sia/issues/2374 is related to this issue, and we should keep watching that issue.

**Comment by jkawamoto** [comment]
Currently, this issue is fixed by disabling host module.
