### ISSUE TITLE
Socket write error when opening folders still synchronizing

### ISSUE THREAD

**Issue by jkawamoto** [GooBox/goobox-sync-sia#49]
The exception came from the icon overlay library, but need further investigation:
```
2018-02-15 23:41:02 [pool-1-thread-4] ERROR c.l.n.control.win.MessageProcessor - Software caused connection abort: socket write error
java.net.SocketException: Software caused connection abort: socket write error
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
    at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
    at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:316)
    at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149)
    at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233)
    at com.liferay.nativity.control.win.MessageProcessor._handle(MessageProcessor.java:110)
    at com.liferay.nativity.control.win.MessageProcessor.run(MessageProcessor.java:70)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by jkawamoto** [comment]
This one should be moved to https://github.com/GooBox/goobox-sync-common/issues and I'll close it.
