### ISSUE TITLE
ERRORs: "Failed walking the file tree" and "java.nio.file.AccessDeniedException"

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-sync-sia#50]
[sia-sync.log](https://github.com/GooBox/goobox-sync-sia/files/1740367/sia-sync.log)
[log.log](https://github.com/GooBox/goobox-sync-sia/files/1740372/log.log)
[renter.log](https://github.com/GooBox/goobox-sync-sia/files/1740375/renter.log)
[contractor.log](https://github.com/GooBox/goobox-sync-sia/files/1740376/contractor.log)
[hostdb.log](https://github.com/GooBox/goobox-sync-sia/files/1740377/hostdb.log)

**Comment by jkawamoto** [comment]
The main exception is 

```
java.io.UncheckedIOException: java.nio.file.AccessDeniedException: C:\Users\meije\Goobox\mocks\goobox-community-gui-prototype\goobox-community-gui-prototype\proto\assets
	at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:88)
	at java.nio.file.FileTreeIterator.hasNext(FileTreeIterator.java:104)
	at java.util.Iterator.forEachRemaining(Iterator.java:115)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:474)
	at io.goobox.sync.common.overlay.OverlayHelper.getIconForFile(OverlayHelper.java:183)
	at com.liferay.nativity.modules.fileicon.FileIconControlBase.getIconForFile(FileIconControlBase.java:68)
	at com.liferay.nativity.modules.fileicon.FileIconControlBase$1.onMessage(FileIconControlBase.java:55)
	at com.liferay.nativity.control.NativityControl.fireMessage(NativityControl.java:104)
	at com.liferay.nativity.control.win.MessageProcessor._handle(MessageProcessor.java:91)
	at com.liferay.nativity.control.win.MessageProcessor.run(MessageProcessor.java:70)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.file.AccessDeniedException: C:\Users\meije\Goobox\mocks\goobox-community-gui-prototype\goobox-community-gui-prototype\proto\assets
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsDirectoryStream.<init>(WindowsDirectoryStream.java:86)
	at sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(WindowsFileSystemProvider.java:518)
	at java.nio.file.Files.newDirectoryStream(Files.java:457)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:300)
	at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:372)
	at java.nio.file.FileTreeIterator.fetchNextIfNeeded(FileTreeIterator.java:84)
	... 17 common frames omitted
```

and it should be handled in https://github.com/GooBox/goobox-sync-common

**Comment by jkawamoto** [comment]
This one is moved to https://github.com/GooBox/goobox-sync-common/issues/13
